language: ruby
cache: bundler
gemfile: ./Gemfile
script:
  - bundle exec jekyll build
  #algolia --source ./ --destination ./_site --config ./_config.yml
branches:
  only:
  - gh-pages
  - /.*/
rvm:
 - 2.6
